"""Urunan sync relay — a zero-storage WebSocket message forwarder.

Devices in the same room (keyed by an unguessable syncId) exchange
end-to-end-encrypted trip snapshots; this server only forwards frames
between currently-connected peers and keeps nothing: no database, no
disk, no logs of payloads. If a room has one member, frames go nowhere.

The syncId is a 128-bit capability token generated by the client; the
AES key never reaches this server (it travels in the share URL's
#fragment). Frames are opaque ciphertext to us.
"""

import asyncio
import os
import re

from fastapi import FastAPI, WebSocket, WebSocketDisconnect

SYNC_ID_RE = re.compile(r"^[A-Za-z0-9_-]{20,30}$")
MAX_FRAME_BYTES = 256 * 1024
# Comma-separated Origin allowlist; empty = allow any (local dev).
ALLOWED_ORIGINS = [o.strip() for o in os.environ.get("ALLOWED_ORIGINS", "").split(",") if o.strip()]

app = FastAPI()

rooms: dict[str, set[WebSocket]] = {}
rooms_lock = asyncio.Lock()


@app.get("/healthz")
async def healthz():
    return {"status": "ok"}


async def _notify_peers(room: set[WebSocket]) -> None:
    """Tell every member how many peers (excluding themselves) are present."""
    n = len(room)
    for ws in list(room):
        try:
            await ws.send_json({"t": "peers", "n": n - 1})
        except Exception:
            pass  # dead socket; its own receive loop will clean it up


@app.websocket("/v1/ws/{sync_id}")
async def relay(ws: WebSocket, sync_id: str):
    if not SYNC_ID_RE.match(sync_id):
        await ws.close(code=1008)
        return
    origin = ws.headers.get("origin", "")
    if ALLOWED_ORIGINS and origin not in ALLOWED_ORIGINS:
        await ws.close(code=1008)
        return

    await ws.accept()
    async with rooms_lock:
        room = rooms.setdefault(sync_id, set())
        room.add(ws)
        await _notify_peers(room)

    try:
        while True:
            frame = await ws.receive_text()
            if len(frame.encode()) > MAX_FRAME_BYTES:
                continue  # drop oversized frames, keep the connection
            async with rooms_lock:
                peers = [p for p in rooms.get(sync_id, ()) if p is not ws]
            for peer in peers:
                try:
                    await peer.send_text(frame)
                except Exception:
                    pass
    except WebSocketDisconnect:
        pass
    finally:
        async with rooms_lock:
            room = rooms.get(sync_id)
            if room is not None:
                room.discard(ws)
                if room:
                    await _notify_peers(room)
                else:
                    del rooms[sync_id]
